### ISSUE TITLE
Amazon.BedrockRuntime.Model.ToolInputSchema does not pass validation for Converse API

### ISSUE THREAD

**Issue by techthoughts2** [aws/aws-tools-for-powershell#354]
### Describe the bug

Amazon Bedrock supports the [Converse API](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html) which supports [tool use](https://docs.aws.amazon.com/bedrock/latest/userguide/tool-use.html).

This requires an [Amazon.BedrockRuntime.Model.Tool](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/BedrockRuntime/TTool.html) to be constructed with a [Amazon.BedrockRuntime.Model.ToolSpecification](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/BedrockRuntime/TToolSpecification.html) and [Amazon.BedrockRuntime.Model.ToolInputSchema](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/BedrockRuntime/TToolInputSchema.html).

I am able to construct this object without issue, however - when it is passed to the Converse API, the input schema always fails validation.

As I am able to engage the Converse API with tool use outside of .NET I believe something in the way the `ToolInputSchema` is being formed by `aws-sdk-net` does not meet the Converse API validation criteria.

### Expected Behavior

I am attempting to craft and send the basic tool use example to the Converse API that is provided in the AWS documentation: https://docs.aws.amazon.com/bedrock/latest/userguide/tool-use.html

Expected behavior is a standard response from the model with a `tool_use` return.

### Current Behavior

When attempting to send the basic tool use example to the Converse API that is provided in the AWS documentation an error is encountered:

`Invoke-BDRRConverse: The format of the value at toolConfig.tools.0.toolSpec.inputSchema.json is invalid. Provide a json object for the field and try again.`

Additional error details:

```
PSMessageDetails      : 
Exception             : System.InvalidOperationException: The format of the value at toolConfig.tools.0.toolSpec.inputSchema.json is invalid. Provide a json object     
                        for the field and try again.
                         ---> Amazon.BedrockRuntime.Model.ValidationException: The format of the value at toolConfig.tools.0.toolSpec.inputSchema.json is invalid.      
                        Provide a json object for the field and try again.
                         ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.    
                           at Amazon.Runtime.HttpWebRequestMessage.ProcessHttpResponseMessage(HttpResponseMessage responseMessage)
                           at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
                           at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
                           --- End of inner exception stack trace ---
                           at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData
                        httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
                           at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext,
                        HttpErrorResponseException exception)
                           at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
                           at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
                           at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
                           at Amazon.PowerShell.Cmdlets.BDRR.InvokeBDRRConverseCmdlet.CallAWSServiceOperation(IAmazonBedrockRuntime client, ConverseRequest request)    
                           at Amazon.PowerShell.Cmdlets.BDRR.InvokeBDRRConverseCmdlet.Execute(ExecutorContext context)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
TargetObject          : Amazon.PowerShell.Cmdlets.BDRR.InvokeBDRRConverseCmdlet
CategoryInfo          : InvalidOperation: (Amazon.PowerShell.C…eBDRRConverseCmdlet:InvokeBDRRConverseCmdlet) [Invoke-BDRRConverse], InvalidOperationException
FullyQualifiedErrorId : Amazon.BedrockRuntime.Model.ValidationException,Amazon.PowerShell.Cmdlets.BDRR.InvokeBDRRConverseCmdlet
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

```
TargetSite     : Void ThrowTerminatingError(System.Management.Automation.ErrorRecord)
Message        : The format of the value at toolConfig.tools.0.toolSpec.inputSchema.json is invalid. Provide a json object for the field and try again.
Data           : {}
InnerException : Amazon.BedrockRuntime.Model.ValidationException: The format of the value at toolConfig.tools.0.toolSpec.inputSchema.json is invalid. Provide a json    
                 object for the field and try again.
                  ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
                    at Amazon.Runtime.HttpWebRequestMessage.ProcessHttpResponseMessage(HttpResponseMessage responseMessage)
                    at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
                    at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
                    --- End of inner exception stack trace ---
                    at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData
                 httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
                    at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException    
                 exception)
                    at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
                    at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
                    at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
                    at Amazon.PowerShell.Cmdlets.BDRR.InvokeBDRRConverseCmdlet.CallAWSServiceOperation(IAmazonBedrockRuntime client, ConverseRequest request)
                    at Amazon.PowerShell.Cmdlets.BDRR.InvokeBDRRConverseCmdlet.Execute(ExecutorContext context)
HelpLink       : 
Source         : System.Management.Automation
HResult        : -2146233079
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
```

### Reproduction Steps

```powershell
# ____________________________________________________________________________
# construct tool 
$tool = [Amazon.BedrockRuntime.Model.Tool]::new()
$toolspec = [Amazon.BedrockRuntime.Model.ToolSpecification]::new()
$toolspec.Name = 'top_song'
$toolspec.Description = 'Get the most popular song played on a radio station.'
$toolspecInputSchema = [Amazon.BedrockRuntime.Model.ToolInputSchema]::new()
$schemaObj = [ordered]@{
    type       = 'object'
    properties = @{
        sign = @{
            type        = 'string'
            description = 'The call sign for the radio station for which you want the most popular song. Example calls signs are WZPZ and WKRP.'
        }
    }
    required   = @(
        'sign'
    )
}
$toolspecInputSchema.Json = $schemaObj | ConvertTo-Json -Depth 10
$toolspec.InputSchema = $toolspecInputSchema
$tool.ToolSpec = $toolspec
# ____________________________________________________________________________
# construct message
$messages = New-Object System.Collections.Generic.List[object]
$message = [Amazon.BedrockRuntime.Model.Message]::new()
$message.Role = 'user'

$content = [Amazon.BedrockRuntime.Model.ContentBlock]::new()
$content.Text = 'What is the most popular song on WZPZ?'
$message.Content = $content
# ____________________________________________________________________________
Invoke-BDRRConverse -ModelId 'anthropic.claude-3-sonnet-20240229-v1:0' -Region us-west-2 -Credential $awsCredential -Message $message -ToolConfig_Tool $tool
```

### Additional Information/Context

It is possible that some assumptions I'm making in the `Tool`, `ToolSpecification`, and `ToolInputSchema` are incorrect.
However, I have tried a multitude of different approaches and varying changes to the formatting of the schema and I have not had any success with the Converse API accepting the `inputSchema.json`

### AWS .NET SDK and/or Package version used

`AWSSDK.BedrockRuntime 3.7.306.6`

### Targeted .NET Platform

.NET Core 7.0.5

### Operating System and version

Microsoft Windows 10.0.22000

**Comment by afroz429** [comment]
@techthoughts2 Changing this line from `$toolspecInputSchema.Json = $schemaObj | ConvertTo-Json -Depth 10` to `$toolspecInputSchema.Json = [Amazon.Runtime.Documents.Document]::FromObject($schemaObj)` seems to work. 

The type of [Json](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/BedrockRuntime/TToolInputSchema.html) is `Amazon.Runtime.Documents.Document` and there is a static method [FromObject](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TDocument.html) that seems to be able to convert a PowerShell hashtable to Document.

I am exploring if there is a more PowerShell idiomatic way to do this. If not we will have to explore if the `Document` handling can be improved.

**Comment by bhoradc** [comment]
Hi @techthoughts2, 

Could you please take a look at comments provided by @afroz429 above, and let us know if it works in your case. 

Regards, 
Chaitanya

**Comment by techthoughts2** [comment]
Confirmed that the suggestion works. Thanks!

**Comment by bhoradc** [comment]
Hi @techthoughts2, 

Thanks for the confirmation. I will therefore go ahead and close this issue. 

Regards, 
Chaitanya
